<img src="exam_result.jpeg" alt="exam_result image" width="49%"/> <img src="examB.png" alt="Lower exam grade image" width="49%"/>

In today's fast-paced and competitive educational environment, understanding the factors that influence student success is more important than ever. Just like the transport system in a bustling city like London must adapt to serve its residents, schools and educators must adapt to meet the needs of students. In this project, we will take a deep dive into a dataset containing rich details about various aspects of student life, such as hours studied, sleep patterns, attendance, and more, to uncover what truly impacts exam performance.

The dataset we'll be working with includes a wide range of factors influencing student performance. By analyzing this data, we'll be able to identify key drivers of success and provide insights that could help students, teachers, and policymakers make informed decisions. The table we'll use for this project is called `student_performance` and includes the following data:

| Column                   | Definition                                                      | Data type             |
|--------------------------|-----------------------------------------------------------------|-----------------------|
| `attendance`              | Percentage of classes attended                                  |     `float`               |
| `extracurricular_activities` | Participation in extracurricular activities                   |     `varchar` (Yes, No)    |
| `sleep_hours`             | Average number of hours of sleep per night                      |     `float`               |
| `tutoring_sessions`       | Number of tutoring sessions attended per month                  |     `integer`             |
| `teacher_quality`         | Quality of the teachers                                         |     `varchar` (Low, Medium, High) |
| `exam_score`              | Final exam score                                                |     `float`               |

You will execute SQL queries to answer three questions, as listed in the instructions.

In [21]:
SELECT * FROM public.student_performance

      hours_studied  attendance  ... tutoring_sessions  exam_score
0                23          84  ...                 0          67
1                19          64  ...                 2          61
2                24          98  ...                 2          74
3                29          89  ...                 1          71
4                19          92  ...                 3          70
...             ...         ...  ...               ...         ...
6602             25          69  ...                 1          68
6603             23          76  ...                 3          69
6604             20          90  ...                 3          68
6605             10          86  ...                 2          68
6606             15          67  ...                 0          64

[6607 rows x 6 columns]

In [22]:
-- avg_exam_score_by_study_and_extracurricular
-- Edit the query below as needed

SELECT
	hours_studied,
	AVG(exam_score) avg_exam_score
FROM student_performance
WHERE 
	hours_studied > 10 
	AND extracurricular_activities = 'Yes'
GROUP BY hours_studied
ORDER BY avg_exam_score DESC

    hours_studied  avg_exam_score
0              43       78.000000
1              39       75.000000
2              38       73.500000
3              37       73.000000
4              35       72.312500
5              30       71.432836
6              32       71.325000
7              34       71.187500
8              31       70.553191
9              36       70.428571
10             33       70.333333
11             29       70.256098
12             28       69.825688
13             27       69.776860
14             25       69.000000
15             26       68.801370
16             24       68.483871
17             23       68.207469
18             22       67.721519
19             21       67.710425
20             20       67.218638
21             19       67.211765
22             18       67.024000
23             16       66.586047
24             17       66.401826
25             15       65.901099
26             14       65.862275
27             11       65.145833
28             13       64.976190
29             12       64.966102

In [23]:
-- avg_exam_score_by_hours_studied_range
-- Add solution code below 

SELECT 
	CASE 
		WHEN hours_studied <= 5 THEN '1-5 hours'
		WHEN hours_studied <= 10 THEN '6-10 hours'
		WHEN hours_studied <= 15 THEN '11-15 hours'
		ELSE '16+ hours'
	END hours_studied_range,
	AVG(exam_score) avg_exam_score
FROM public.student_performance
GROUP BY hours_studied_range
ORDER BY avg_exam_score DESC

  hours_studied_range  avg_exam_score
0           16+ hours       67.923363
1         11-15 hours       65.204386
2          6-10 hours       64.225490
3           1-5 hours       62.627119

In [24]:
-- student_exam_ranking
-- Add solution code below 

SELECT
	attendance,
	hours_studied,
	sleep_hours,
	tutoring_sessions,
	DENSE_RANK() OVER(ORDER BY exam_score DESC) exam_rank
FROM public.student_performance
ORDER BY exam_rank ASC
LIMIT 30

    attendance  hours_studied  sleep_hours  tutoring_sessions  exam_rank
0           98             27            6                  5          1
1           89             18            4                  3          2
2           90             14            8                  4          3
3           83             23            4                  1          3
4           96             28            4                  1          4
5           90             28            9                  0          4
6           83             16            8                  2          4
7           83             15            7                  2          5
8           74             21            6                  1          5
9           99             25            7                  0          5
10          93             18            7                  2          6
11          90             18            6                  1          7
12          67             21            6                  1          7
13          96             24            6                  2          8
14          98             25            7                  1          8
15          76             29            8                  2          8
16          90             19            5                  0          8
17          69             26            7                  0          9
18          73             25            7                  2          9
19          88              1            4                  3         10
20          69             31            7                  2         10
21          70             21            9                  1         11
22          77             14            6                  1         12
23          92             21            9                  2         12
24          70             19            7                  0         12
25          86             18            8                  2         13
26          98             30            9                  1         13
27          62             11            7                  3         13
28          71             11            8                  1         14
29          69              7            8                  1         14